from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LOCK = json.loads((ROOT / "manuscript" / "certified_run_counts.json").read_text(encoding="utf-8"))
RUN_HASH = str(LOCK["run_hash"])
CSV_PATH = ROOT / "outputs" / RUN_HASH / "summary" / "adequacy_operating_characteristic.csv"
OUTPUT_TABLE = ROOT / "outputs" / RUN_HASH / "tables" / "adequacy_operating_characteristic.tex"
MANUSCRIPT_TABLE = ROOT / "manuscript" / "tables" / "adequacy_operating_characteristic.tex"

EXPECTED_DELTAS = [20.0, 30.0, 40.0, 50.0, 60.0, 75.0, 90.0]
P_FA_MAX = 0.05


def _rows() -> list[dict[str, str]]:
    with CSV_PATH.open(newline="", encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def test_adequacy_csv_exists_and_has_declared_grid() -> None:
    assert CSV_PATH.exists()

    rows = _rows()
    assert len(rows) == 14

    for direction in ("negative", "positive"):
        got = sorted(float(row["delta"]) for row in rows if row["direction"] == direction)
        assert got == EXPECTED_DELTAS


def test_adequacy_certificate_is_monotone_wilson_envelope() -> None:
    rows = _rows()

    for direction in ("negative", "positive"):
        group = sorted(
            [row for row in rows if row["direction"] == direction],
            key=lambda row: float(row["delta"]),
        )

        certified = [row for row in group if row["envelope_pass"] == "true"]
        assert certified, f"no certified delta for {direction}"

        certified_delta = float(certified[0]["delta"])

        for row in group:
            delta = float(row["delta"])
            rate = float(row["false_adequacy_rate"])
            envelope_high = float(row["envelope_wilson95_high"])

            if delta >= certified_delta:
                assert rate <= P_FA_MAX
                assert envelope_high <= P_FA_MAX
                assert row["envelope_pass"] == "true"
            else:
                assert row["envelope_pass"] == "false"

            assert float(row["certified_delta_direction"]) == certified_delta

    by_direction = {}
    for direction in ("negative", "positive"):
        values = {
            float(row["certified_delta_direction"])
            for row in rows
            if row["direction"] == direction and row["certified_delta_direction"]
        }
        assert len(values) == 1
        by_direction[direction] = values.pop()

    expected_pm = max(by_direction.values())
    assert {float(row["certified_delta_pm"]) for row in rows} == {expected_pm}


def test_adequacy_table_copies_match_generated_output() -> None:
    assert OUTPUT_TABLE.exists()
    assert MANUSCRIPT_TABLE.exists()

    generated = OUTPUT_TABLE.read_text(encoding="utf-8")
    assert "Machine-generated by scripts/make_adequacy_operating_characteristic.py" in generated
    assert "\\label{tab:si-adequacy-oc}" in generated
    assert "Envelope UCB" in generated

    import csv

    output_csv = (
        OUTPUT_TABLE.parent.parent
        / "summary"
        / "adequacy_operating_characteristic.csv"
    )
    rows = list(
        csv.DictReader(output_csv.read_text(encoding="utf-8").splitlines())
    )

    statuses = []
    for line in generated.splitlines():
        tail = line.rsplit("&", 1)[-1].strip()
        if tail == r"pass \\":
            statuses.append("pass")
        elif tail == r"fail \\":
            statuses.append("fail")

    # Every CSV operating-characteristic row must receive exactly one valid
    # pass/fail status in the generated table. A particular certified run need
    # not contain both statuses.
    assert len(statuses) == len(rows)
    assert set(statuses) <= {"pass", "fail"}
    assert "pass" in statuses

    assert MANUSCRIPT_TABLE.read_text(encoding="utf-8") == generated
