#!/usr/bin/env python3
"""Generate the magnitude-indexed adequacy operating characteristic.

This sweep is the false-null-certification analogue of a power curve. For each
injected endpoint-level slope magnitude delta, it estimates the probability that
the final non-compensatory classifier returns forward_only_adequate even though a
genuine endpoint-level residual of that magnitude is present.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import shutil
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

from cri_leveliia import benchmarks as B  # noqa: E402
from make_false_adequacy_rates import P_FA_MAX, _wilson_interval  # noqa: E402


DEFAULT_DELTAS = [20.0, 30.0, 40.0, 50.0, 60.0, 75.0, 90.0]

DIRECTIONS = [
    {
        "direction": "negative",
        "symbol": "FA_-",
        "config": "injected_residual.yaml",
        "sign": -1.0,
        "raw_prefix": "adequacy_negative",
        "generator": "endpoint_injected_negative_sweep",
    },
    {
        "direction": "positive",
        "symbol": "FA_+",
        "config": "opposite_direction.yaml",
        "sign": 1.0,
        "raw_prefix": "adequacy_positive",
        "generator": "endpoint_injected_positive_sweep",
    },
]

CSV_COLUMNS = [
    "sweep_id",
    "run_hash",
    "direction",
    "beta_inj",
    "delta",
    "beta_min_med",
    "delta_over_beta_min",
    "M",
    "false_adequacy_n",
    "false_adequacy_rate",
    "wilson95_low",
    "wilson95_high",
    "envelope_wilson95_high",
    "p_fa_max",
    "envelope_pass",
    "certified_delta_direction",
    "certified_delta_pm",
    "support_n",
    "support_rate",
    "opposite_direction_n",
    "opposite_direction_rate",
    "selection_limited_n",
    "selection_limited_rate",
    "diagnostic_failure_n",
    "diagnostic_failure_rate",
    "inconclusive_n",
    "inconclusive_rate",
    "base_seed",
    "source_raw_csv",
]


def _read_latest_run_hash(outdir: Path) -> str:
    latest = outdir / "LATEST_RUN.txt"
    if not latest.exists():
        raise FileNotFoundError(
            f"No run hash supplied and {latest} does not exist. "
            "Run scripts/run_all.py --all first or pass --run-hash."
        )
    return latest.read_text(encoding="utf-8").strip()


def _load_yaml(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def _parse_deltas(text: str | None) -> list[float]:
    if not text:
        return list(DEFAULT_DELTAS)

    values = [float(x.strip()) for x in text.split(",") if x.strip()]
    if not values:
        raise ValueError("The delta grid is empty.")
    if any(v <= 0 for v in values):
        raise ValueError(f"All delta magnitudes must be positive: {values}")

    return sorted(set(values))


def _delta_tag(delta: float) -> str:
    return f"{delta:g}".replace(".", "p").replace("-", "m")


def _fmt6(value: float) -> str:
    return f"{float(value):.6f}"


def _fmt1(value: float) -> str:
    return f"{float(value):.1f}"


def _sweep_id(run_hash: str, m: int, deltas: list[float]) -> str:
    payload = "|".join([run_hash, f"M={m}", ",".join(f"{d:g}" for d in deltas)])
    digest = hashlib.sha1(payload.encode("utf-8")).hexdigest()[:16]
    return f"adequacy_{digest}"


def _rate_count(n: int, m: int) -> str:
    return f"{n}/{m} ({n / m:.3f})"


def _truefalse(value: bool) -> str:
    return "true" if value else "false"


def _latex_bool(value: str) -> str:
    return "pass" if str(value).lower() == "true" else "fail"


def _write_csv(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=CSV_COLUMNS)
        writer.writeheader()
        writer.writerows(rows)


def _write_table(
    path: Path,
    rows: list[dict[str, str]],
    run_hash: str,
    sweep_id: str,
    m: int,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "% Machine-generated by scripts/make_adequacy_operating_characteristic.py; do not edit by hand.",
        f"% Source: outputs/{run_hash}/summary/adequacy_operating_characteristic.csv; sweep_id={sweep_id}",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{Adequacy operating characteristic for the certified Level~II-A pipeline. Each row reports the probability that a dataset with a genuine endpoint-level injected residual of magnitude \\(\\delta\\) is nevertheless classified as forward-only adequate. Intervals are Wilson \\(95\\%\\) binomial intervals from \\(M={m}\\) Monte Carlo datasets. Certification requires the monotone Wilson upper-bound envelope at that magnitude and all larger evaluated magnitudes to be at or below \\(p_{{\\mathrm{{FA,max}}}}=0.05\\). The table is generated by the executable benchmark sweep and is not human EEG evidence.}}",
        "\\label{tab:si-adequacy-oc}",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{llrrrrr}",
        "\\toprule",
        "Direction & \\(\\delta\\) & \\(\\delta/\\beta_{\\min}\\) & False adequacy & Wilson \\(95\\%\\) & Envelope UCB & Envelope \\\\",
        "\\midrule",
    ]

    for row in rows:
        direction = "negative" if row["direction"] == "negative" else "positive"
        delta = f"\\({_fmt1(float(row['delta']))}\\)"
        ratio = f"\\({_fmt6(float(row['delta_over_beta_min']))}\\)"
        false_adequacy = _rate_count(int(row["false_adequacy_n"]), int(row["M"]))
        interval = f"\\([{_fmt6(float(row['wilson95_low']))},{_fmt6(float(row['wilson95_high']))}]\\)"
        envelope = f"\\({_fmt6(float(row['envelope_wilson95_high']))}\\)"
        passed = _latex_bool(row["envelope_pass"])

        lines.append(
            " & ".join(
                [
                    direction,
                    delta,
                    ratio,
                    false_adequacy,
                    interval,
                    envelope,
                    passed,
                ]
            )
            + " \\\\"
        )

    lines.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
        ]
    )

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _apply_envelope(rows: list[dict[str, str]]) -> None:
    certified: dict[str, float | None] = {}

    for direction in sorted({row["direction"] for row in rows}):
        group = sorted(
            [row for row in rows if row["direction"] == direction],
            key=lambda r: float(r["delta"]),
        )

        highs = [float(row["wilson95_high"]) for row in group]
        envelope_highs = []

        for i in range(len(group)):
            envelope_highs.append(max(highs[i:]))

        direction_certified = None

        for row, env_high in zip(group, envelope_highs):
            rate = float(row["false_adequacy_rate"])
            passed = (rate <= P_FA_MAX) and (env_high <= P_FA_MAX)

            row["envelope_wilson95_high"] = _fmt6(env_high)
            row["envelope_pass"] = _truefalse(passed)

            if passed and direction_certified is None:
                direction_certified = float(row["delta"])

        certified[direction] = direction_certified

        for row in group:
            row["certified_delta_direction"] = (
                "" if direction_certified is None else _fmt6(direction_certified)
            )

    if certified.get("negative") is not None and certified.get("positive") is not None:
        pm = max(float(certified["negative"]), float(certified["positive"]))
        pm_text = _fmt6(pm)
    else:
        pm_text = ""

    for row in rows:
        row["certified_delta_pm"] = pm_text


def run_sweep(
    run_hash: str,
    m: int,
    deltas: list[float],
    overwrite: bool,
    copy_tables: bool,
) -> Path:
    out_root = ROOT / "outputs"
    run_dir = out_root / run_hash

    if not run_dir.exists():
        raise FileNotFoundError(f"Run directory does not exist: {run_dir}")

    summary_dir = run_dir / "summary"
    raw_dir = run_dir / "raw"
    table_dir = run_dir / "tables"
    metadata_dir = run_dir / "metadata"

    for path in (summary_dir, raw_dir, table_dir, metadata_dir):
        path.mkdir(parents=True, exist_ok=True)

    sweep_id = _sweep_id(run_hash, m, deltas)

    csv_path = summary_dir / "adequacy_operating_characteristic.csv"
    table_path = table_dir / "adequacy_operating_characteristic.tex"
    metadata_path = metadata_dir / "adequacy_sweep_metadata.json"

    if (csv_path.exists() or table_path.exists()) and not overwrite:
        raise FileExistsError(
            "Adequacy operating-characteristic outputs already exist. "
            "Pass --overwrite to regenerate them."
        )

    rows: list[dict[str, str]] = []

    for meta in DIRECTIONS:
        base_cfg = _load_yaml(ROOT / "configs" / meta["config"])

        for delta in deltas:
            cfg = dict(base_cfg)
            cfg["name"] = f"adequacy_{meta['direction']}_delta_{_delta_tag(delta)}"
            cfg["generator"] = meta["generator"]
            cfg["beta_inj"] = meta["sign"] * float(delta)
            cfg["base_seed"] = int(base_cfg["base_seed"])

            print(
                f"[adequacy] {meta['direction']:8s} delta={delta:g} "
                f"beta_inj={cfg['beta_inj']:g} M={m}",
                flush=True,
            )

            df = B.run_scenario(cfg, M=m, base_seed=cfg["base_seed"])

            raw_name = f"{meta['raw_prefix']}_delta_{_delta_tag(delta)}.csv"
            raw_path = raw_dir / raw_name
            df.to_csv(raw_path, index=False)

            summary = B.summarise(df, cfg, cfg["name"], cfg["generator"])
            fa_n = int(summary["null_n"])
            low, high = _wilson_interval(fa_n, int(summary["M"]))
            beta_min = float(summary["beta_min_med"])

            rows.append(
                {
                    "sweep_id": sweep_id,
                    "run_hash": run_hash,
                    "direction": meta["direction"],
                    "beta_inj": _fmt6(summary["beta_inj"]),
                    "delta": _fmt6(delta),
                    "beta_min_med": _fmt6(beta_min),
                    "delta_over_beta_min": _fmt6(delta / beta_min),
                    "M": str(int(summary["M"])),
                    "false_adequacy_n": str(fa_n),
                    "false_adequacy_rate": _fmt6(fa_n / int(summary["M"])),
                    "wilson95_low": _fmt6(low),
                    "wilson95_high": _fmt6(high),
                    "envelope_wilson95_high": "",
                    "p_fa_max": _fmt6(P_FA_MAX),
                    "envelope_pass": "",
                    "certified_delta_direction": "",
                    "certified_delta_pm": "",
                    "support_n": str(int(summary["support_n"])),
                    "support_rate": _fmt6(summary["support_rate"]),
                    "opposite_direction_n": str(int(summary["opposite_direction_n"])),
                    "opposite_direction_rate": _fmt6(summary["opposite_direction_rate"]),
                    "selection_limited_n": str(int(summary["selection_limited_n"])),
                    "selection_limited_rate": _fmt6(summary["selection_limited_rate"]),
                    "diagnostic_failure_n": str(int(summary["diagnostic_failure_n"])),
                    "diagnostic_failure_rate": _fmt6(summary["diagnostic_failure_rate"]),
                    "inconclusive_n": str(int(summary["inconclusive_n"])),
                    "inconclusive_rate": _fmt6(summary["inconclusive_rate"]),
                    "base_seed": str(cfg["base_seed"]),
                    "source_raw_csv": f"outputs/{run_hash}/raw/{raw_name}",
                }
            )

    _apply_envelope(rows)

    rows = sorted(rows, key=lambda r: (r["direction"], float(r["delta"])))

    _write_csv(csv_path, rows)
    _write_table(table_path, rows, run_hash=run_hash, sweep_id=sweep_id, m=m)

    metadata = {
        "sweep_id": sweep_id,
        "run_hash": run_hash,
        "M": m,
        "deltas": deltas,
        "p_fa_max": P_FA_MAX,
        "certification_rule": "monotone_wilson95_high_envelope_le_p_fa_max",
        "source_script": "scripts/make_adequacy_operating_characteristic.py",
        "csv": f"outputs/{run_hash}/summary/adequacy_operating_characteristic.csv",
        "table": f"outputs/{run_hash}/tables/adequacy_operating_characteristic.tex",
    }

    metadata_path.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")

    if copy_tables:
        dst_dir = ROOT / "manuscript" / "tables"
        dst_dir.mkdir(parents=True, exist_ok=True)
        shutil.copy2(table_path, dst_dir / table_path.name)

    print(f"[adequacy] wrote {csv_path}")
    print(f"[adequacy] wrote {table_path}")

    for direction in ("negative", "positive"):
        values = {
            r["certified_delta_direction"]
            for r in rows
            if r["direction"] == direction
        }
        print(
            f"[adequacy] certified_delta_{direction}="
            f"{sorted(values)[0] if values else ''}"
        )

    pm = {r["certified_delta_pm"] for r in rows if r["certified_delta_pm"]}
    print(f"[adequacy] certified_delta_pm={sorted(pm)[0] if pm else ''}")

    return csv_path


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-hash", default=None)
    ap.add_argument("--M", type=int, default=1200)
    ap.add_argument(
        "--deltas",
        default=",".join(f"{d:g}" for d in DEFAULT_DELTAS),
    )
    ap.add_argument("--overwrite", action="store_true")
    ap.add_argument("--no-copy", action="store_true")
    args = ap.parse_args()

    if args.M <= 0:
        raise ValueError("M must be positive")

    run_hash = args.run_hash or _read_latest_run_hash(ROOT / "outputs")
    deltas = _parse_deltas(args.deltas)

    run_sweep(
        run_hash=run_hash,
        m=args.M,
        deltas=deltas,
        overwrite=args.overwrite,
        copy_tables=not args.no_copy,
    )


if __name__ == "__main__":
    main()
