from pathlib import Path
import json
import pandas as pd

RUN_HASH = "9d2658d6d147de10"
ROOT = Path(__file__).resolve().parents[1]
RUN_DIR = ROOT / "outputs" / RUN_HASH
OUT = ROOT / "CRI_Perspective" / "Tables" / "worked_decision_example.tex"

rep_path = RUN_DIR / "summary" / "representative_index.json"
with open(rep_path, "r", encoding="utf-8") as f:
    reps = json.load(f)

inj_rep = int(reps["injected_residual"]["replicate"])
null_rep = int(reps["anchor"]["replicate"])

inj = pd.read_csv(RUN_DIR / "raw" / "injected_residual.csv")
nul = pd.read_csv(RUN_DIR / "raw" / "anchor.csv")

inj_row = inj.loc[inj["replicate"] == inj_rep].iloc[0]
nul_row = nul.loc[nul["replicate"] == null_rep].iloc[0]

def get(row, name, default="---"):
    return row[name] if name in row.index else default

def fmt(x, nd=1):
    try:
        return f"{float(x):.{nd}f}"
    except Exception:
        return str(x)

def fmtp(x):
    try:
        x = float(x)
        return f"{x:.1e}" if x < 0.001 else f"{x:.3f}"
    except Exception:
        return str(x)

OUT.parent.mkdir(parents=True, exist_ok=True)

tex = rf"""
% Machine-generated by scripts/make_worked_example.py.
% Frozen run hash: {RUN_HASH}.

The worked example is generated from the same frozen benchmark output directory
as the operating-characteristics table. For run \texttt{{{RUN_HASH}}}, the
representative supported injected-residual draw is replicate \({inj_rep}\), and
the representative clean-null draw is replicate \({null_rep}\). These values are
read directly from the frozen raw per-replicate CSV files, not transcribed by
hand.

\begin{{table}}[t]
\centering
\caption{{Every decision object available in the frozen per-replicate benchmark
rows for the representative supported injected-residual draw and the
representative clean-null draw. Slope, bound and floor units are
\(\mu\mathrm{{V\,s^{{-1}}}}\).}}
\label{{tab:si-worked-decision}}
\begin{{tabular}}{{lccc}}
\toprule
Decision object & Criterion & Supported draw & Clean-null draw \\
\midrule
Scenario & recorded generator & injected residual & clean null \\
Replicate & representative index & \({inj_rep}\) & \({null_rep}\) \\
Decision & executable classifier & \texttt{{{get(inj_row, "decision")}}} & \texttt{{{get(nul_row, "decision")}}} \\
Estimate \(\widehat\beta_\tau\) & reported & \({fmt(get(inj_row, "beta_hat"))}\) & \({fmt(get(nul_row, "beta_hat"))}\) \\
Bootstrap-t \(\mathrm{{UCB}}_{{0.95}}\) & \(<-\beta_{{\min}}\) & \({fmt(get(inj_row, "ucb"))}\) & \({fmt(get(nul_row, "ucb"))}\) \\
Bootstrap-t \(\mathrm{{LCB}}_{{0.95}}\) & reported & \({fmt(get(inj_row, "lcb"))}\) & \({fmt(get(nul_row, "lcb"))}\) \\
Resolution floor \(\beta_{{\min}}\) & registered formula & \({fmt(get(inj_row, "beta_min"))}\) & \({fmt(get(nul_row, "beta_min"))}\) \\
Randomisation \(p\), negative direction & \(\le 0.05\) & \({fmtp(get(inj_row, "p_rand_less"))}\) & \({fmtp(get(nul_row, "p_rand_less"))}\) \\
Randomisation \(p\), positive direction & reported & \({fmtp(get(inj_row, "p_rand_greater"))}\) & \({fmtp(get(nul_row, "p_rand_greater"))}\) \\
Support indicator & final outcome column & \({int(get(inj_row, "supported", 0))}\) & \({int(get(nul_row, "supported", 0))}\) \\
Selection-limited indicator & final outcome column & \({int(get(inj_row, "selection_limited", 0))}\) & \({int(get(nul_row, "selection_limited", 0))}\) \\
Diagnostic-failure indicator & final outcome column & \({int(get(inj_row, "diagnostic_failure", 0))}\) & \({int(get(nul_row, "diagnostic_failure", 0))}\) \\
Null indicator & final outcome column & \({int(get(inj_row, "forward_only_adequate", 0))}\) & \({int(get(nul_row, "forward_only_adequate", 0))}\) \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""

OUT.write_text(tex, encoding="utf-8")
print(f"Wrote {OUT}")
print(f"Injected residual replicate: {inj_rep}")
print(f"Clean-null replicate: {null_rep}")
