#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from pathlib import Path


GENERATOR_LABELS = {
    "forward_only": "Forward-only null",
    "endpoint_injected": "Negative endpoint-level residual",
    "forward_only_with_leak": "Forward-only null with temporal leak",
    "forward_only_monotone_selection": "Forward-only null with monotone selection",
    "forward_only_collider_selection": "Forward-only null with endpoint-by-delay collider",
    "adversarial_forward_only": "Adversarial forward-only null",
    "endpoint_injected_positive": "Positive endpoint-level residual",
}


OUTCOME_COUNT_KEYS = {
    "support_rate": "support_n",
    "selection_limited_rate": "selection_limited_n",
    "diagnostic_failure_rate": "diagnostic_failure_n",
    "null_rate": "null_n",
    "opposite_direction_rate": "opposite_direction_n",
    "inconclusive_rate": "inconclusive_n",
}


DESIGN_COLUMNS = [
    ("scenario", "Scenario", "text"),
    ("generator", "Generator", "generator"),
    ("trials_per_bin", "$n$/bin", "int"),
    ("beta_min_med", "$\\beta_{\\min}$", "num"),
    ("beta_inj", "$\\beta^{\\mathrm{inj}}$", "num"),
    ("mean_beta_hat", "Mean $\\widehat{\\beta}_\\tau$", "num"),
    ("median_ucb", "Med. UCB", "num"),
]


OUTCOME_COLUMNS = [
    ("scenario", "Scenario", "text"),
    ("rand_pass_rate", "rand. pass", "rate"),
    ("materiality_pass_rate", "resol. pass", "rate"),
    ("retention_fire_rate", "reten. fire", "rate"),
    ("leak_fire_rate", "leak fire", "rate"),
    ("gate_pass_rate", "gate pass", "rate"),
    ("collider_fire_rate", "collider fire", "rate"),
    ("support_rate", "support", "count_rate"),
    ("selection_limited_rate", "sel.-lim.", "count_rate"),
    ("diagnostic_failure_rate", "diag. fail", "count_rate"),
    ("null_rate", "null", "count_rate"),
    ("opposite_direction_rate", "opp. dir.", "count_rate"),
]


def latex_escape(value: str) -> str:
    return (
        str(value)
        .replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("#", "\\#")
    )


def fmt_num(value: str) -> str:
    x = float(value)
    if x == 0:
        return "0"
    if abs(x) < 1:
        return f"{x:.3f}"
    return f"{x:.1f}"


def fmt_rate(value: str) -> str:
    return f"{float(value):.3f}"


def fmt_count_rate(row: dict[str, str], rate_key: str) -> str:
    rate = float(row[rate_key])
    count_key = OUTCOME_COUNT_KEYS[rate_key]
    count = int(float(row[count_key]))
    m = int(float(row["M"]))
    return f"{count}/{m} ({rate:.3f})"


def fmt_cell(row: dict[str, str], key: str, kind: str) -> str:
    if kind == "text":
        return latex_escape(row[key])
    if kind == "generator":
        return latex_escape(GENERATOR_LABELS.get(row[key], row[key]))
    if kind == "int":
        return str(int(float(row[key])))
    if kind == "num":
        return fmt_num(row[key])
    if kind == "rate":
        return fmt_rate(row[key])
    if kind == "count_rate":
        return fmt_count_rate(row, key)
    raise ValueError(f"Unknown column kind: {kind}")


def read_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open("r", encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))
    if not rows:
        raise RuntimeError(f"No rows found in {csv_path}")
    return rows


def write_table(
    rows: list[dict[str, str]],
    out_path: Path,
    run_hash: str,
    columns: list[tuple[str, str, str]],
    caption: str,
    label: str,
    tabular_spec: str,
    fontsize: str = "\\scriptsize",
) -> None:
    lines: list[str] = []
    lines.append(f"% Machine-generated by scripts/make_split_oc_tables.py")
    lines.append(f"% Source: outputs/{run_hash}/summary/operating_characteristics.csv")
    lines.append(f"% Frozen run hash: {run_hash}")
    lines.append("% Do not edit by hand.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{" + caption + "}")
    lines.append("\\label{" + label + "}")
    lines.append(fontsize)
    lines.append("\\setlength{\\tabcolsep}{3pt}")
    lines.append("\\begin{tabular}{" + tabular_spec + "}")
    lines.append("\\toprule")
    lines.append(" & ".join(head for _, head, _ in columns) + " \\\\")
    lines.append("\\midrule")

    for row in rows:
        cells = [fmt_cell(row, key, kind) for key, _, kind in columns]
        lines.append(" & ".join(cells) + " \\\\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_split_tables(csv_path: Path, outdir: Path, run_hash: str | None = None) -> None:
    rows = read_rows(csv_path)
    actual_hash = run_hash or rows[0].get("run_hash", "UNKNOWN")
    outdir.mkdir(parents=True, exist_ok=True)

    design_caption = (
        "Benchmark design and slope-resolution summaries for the locked Level II-A "
        "pipeline on simulated data. Rates and decision outcomes are reported separately "
        f"in Table~\\ref{{tab:si-oc-outcomes}}. Run hash \\texttt{{{actual_hash}}}; "
        "$M=1200$ datasets per scenario; $P=24$ participants; assigned-delay support "
        "$[0,20]$ ms; $\\sigma_{\\mathrm{resid}}=1\\,\\mu$V; not human EEG."
    )

    outcome_caption = (
        "Diagnostic rates and mutually exclusive decision outcomes for the locked Level II-A "
        "pipeline on simulated data. Design constants and slope summaries are reported in "
        f"Table~\\ref{{tab:si-oc-design}}. Run hash \\texttt{{{actual_hash}}}; all outcome "
        "cells are exact counts over $M=1200$ Monte Carlo datasets with rates in parentheses; "
        "not human EEG."
    )

    write_table(
        rows=rows,
        out_path=outdir / "operating_characteristics_design.tex",
        run_hash=actual_hash,
        columns=DESIGN_COLUMNS,
        caption=design_caption,
        label="tab:si-oc-design",
        tabular_spec="llrrrrr",
        fontsize="\\footnotesize",
    )

    write_table(
        rows=rows,
        out_path=outdir / "operating_characteristics_outcomes.tex",
        run_hash=actual_hash,
        columns=OUTCOME_COLUMNS,
        caption=outcome_caption,
        label="tab:si-oc-outcomes",
        tabular_spec="lrrrrrrlllll",
        fontsize="\\scriptsize",
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-hash", required=True)
    ap.add_argument("--outdir", default="outputs")
    args = ap.parse_args()

    run_dir = Path(args.outdir) / args.run_hash
    csv_path = run_dir / "summary" / "operating_characteristics.csv"
    table_dir = run_dir / "tables"

    if not csv_path.exists():
        raise FileNotFoundError(csv_path)

    write_split_tables(csv_path=csv_path, outdir=table_dir, run_hash=args.run_hash)
    print(f"[split-oc] wrote {table_dir / 'operating_characteristics_design.tex'}")
    print(f"[split-oc] wrote {table_dir / 'operating_characteristics_outcomes.tex'}")


if __name__ == "__main__":
    main()
