# -*- coding: utf-8 -*-
"""
Created on Sun Jun 28 10:43:17 2026

@author: ADMIN

Table writers for the realised operating characteristics.

All numbers written here originate from the benchmark output; nothing is typed
by hand. The LaTeX writers emit booktabs tables that the manuscript and SI
include.

For mutually exclusive outcome columns, the LaTeX outcome table reports exact
counts over M Monte Carlo datasets with rates in parentheses. This avoids
apparent row-sum discrepancies caused by independently rounded three-decimal
rates.
"""

from __future__ import annotations

import numbers
from pathlib import Path

import pandas as pd


# Current frozen manuscript/SI benchmark run. Writers also infer the run hash
# from paths under outputs/<run_hash>/tables/ and allow explicit override.
DEFAULT_FROZEN_RUN_HASH = "9d2658d6d147de10"


# Ordered columns for the realised operating-characteristics table (SI S9).
OC_COLUMNS = [
    ("scenario", "Scenario"),
    ("generator", "Generator"),
    ("M", "$M$"),
    ("P", "$P$"),
    ("trials_per_bin", "trials/bin"),
    ("delay_support_ms", "support (ms)"),
    ("sigma_resid", "$\\sigma_{\\mathrm{resid}}$"),
    ("beta_min_med", "$\\beta_{\\min}$"),
    ("beta_inj", "$\\beta^{\\mathrm{inj}}$"),
    ("mean_beta_hat", "mean $\\widehat{\\beta}_\\tau$"),
    ("sd_beta_hat", "SD $\\widehat{\\beta}_\\tau$"),
    ("median_ucb", "med.\\ UCB"),
    ("rand_pass_rate", "rand.\\ pass"),
    ("materiality_pass_rate", "resol.\\ pass"),
    ("retention_fire_rate", "reten.\\ fire"),
    ("leak_fire_rate", "leak fire"),
    ("gate_pass_rate", "gate pass"),
    ("collider_fire_rate", "collider fire"),
    ("support_rate", "support"),
    ("selection_limited_rate", "sel.-lim."),
    ("diagnostic_failure_rate", "diag.\\ fail"),
    ("null_rate", "null"),
    ("opposite_direction_rate", "opp.\\ dir."),
]


OUTCOME_RATE_TO_COUNT = {
    "support_rate": "support_n",
    "selection_limited_rate": "selection_limited_n",
    "diagnostic_failure_rate": "diagnostic_failure_n",
    "null_rate": "null_n",
    "opposite_direction_rate": "opposite_direction_n",
    "inconclusive_rate": "inconclusive_n",
}


def _latex_escape_text(v):
    return str(v).replace("_", "\\_")


def _fmt(v):
    if isinstance(v, numbers.Real) and not isinstance(v, bool):
        v = float(v)
        if v == 0:
            return "0"
        if abs(v) < 1 and abs(v) >= 1e-4:
            return f"{v:.3f}"
        if abs(v) >= 1:
            return f"{v:.1f}"
        return f"{v:.2e}"
    return str(v)


def _infer_run_hash_from_path(path):
    """Infer run hash from paths under outputs/<run_hash>/... when possible."""
    if path is None:
        return None

    parts = Path(path).parts
    lowered = [p.lower() for p in parts]

    if "outputs" not in lowered:
        return None

    idx = lowered.index("outputs")
    if idx + 1 >= len(parts):
        return None

    candidate = parts[idx + 1]
    if candidate:
        return candidate

    return None


def _resolve_run_hash(path=None, run_hash=None):
    """Resolve the exact run hash for table provenance."""
    if run_hash:
        return str(run_hash)

    inferred = _infer_run_hash_from_path(path)
    if inferred:
        return inferred

    return DEFAULT_FROZEN_RUN_HASH


def _provenance_header(source_filename, path=None, run_hash=None):
    """Standard exact provenance comments for generated LaTeX tables."""
    resolved_hash = _resolve_run_hash(path=path, run_hash=run_hash)
    source = f"outputs/{resolved_hash}/summary/{source_filename}"

    return [
        (
            "% Machine-generated by scripts/run_all.py / "
            f"src/cri_leveliia/tables.py; run_hash={resolved_hash}; "
            "do not edit by hand."
        ),
        f"% Source: {source}",
    ]


def _fmt_outcome_count_rate(summary, rate_key):
    """Format a mutually exclusive outcome as count/M (rate)."""
    rate = float(summary.get(rate_key, 0.0))
    count_key = OUTCOME_RATE_TO_COUNT[rate_key]
    M = int(summary.get("M", 0))

    if count_key in summary:
        count = int(summary[count_key])
    else:
        count = int(round(rate * M))

    return f"{count}/{M} ({rate:.3f})"


def _fmt_cell(summary, key):
    v = summary.get(key, "")

    if key in OUTCOME_RATE_TO_COUNT:
        return _fmt_outcome_count_rate(summary, key)

    if isinstance(v, str):
        return _latex_escape_text(v)

    return _fmt(v)


def operating_characteristics_csv(summaries, path):
    df = pd.DataFrame(summaries)
    df.to_csv(path, index=False)
    return df


def operating_characteristics_latex(
    summaries,
    path,
    caption,
    label,
    columns=None,
    run_hash=None,
):
    columns = columns or OC_COLUMNS
    keys = [k for k, _ in columns]
    heads = [h for _, h in columns]

    lines = _provenance_header(
        source_filename="operating_characteristics.csv",
        path=path,
        run_hash=run_hash,
    )
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{" + caption + "}")
    lines.append("\\label{" + label + "}")
    lines.append("\\scriptsize")
    lines.append("\\setlength{\\tabcolsep}{3pt}")
    lines.append("\\begin{tabular}{l" + "r" * (len(keys) - 1) + "}")
    lines.append("\\toprule")
    lines.append(" & ".join(heads) + " \\\\")
    lines.append("\\midrule")

    for s in summaries:
        row = [_fmt_cell(s, k) for k in keys]
        lines.append(" & ".join(row) + " \\\\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    return "\n".join(lines)


def collider_subtable_latex(
    summary,
    sweep_df,
    path,
    caption,
    label,
    run_hash=None,
):
    """Dedicated collider scope-test subtable."""
    lines = _provenance_header(
        source_filename="collider_sweep.csv",
        path=path,
        run_hash=run_hash,
    )
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\caption{" + caption + "}")
    lines.append("\\label{" + label + "}")
    lines.append("\\footnotesize")
    lines.append("\\begin{tabular}{lrrrrrr}")
    lines.append("\\toprule")
    lines.append(
        "$\\gamma$ & med.\\ $\\widehat{\\beta}_\\tau$ & marg.\\ imbal. & "
        "reten.\\ fire & resol.\\ pass & interaction fire & sel.-lim. \\\\"
    )
    lines.append("\\midrule")

    for _, r in sweep_df.iterrows():
        lines.append(
            " & ".join(
                [
                    _fmt(r["collider_gamma"]),
                    _fmt(r["median_beta_hat"]),
                    _fmt(r["retention_imbalance_med"]),
                    _fmt(r["retention_fire_rate"]),
                    _fmt(r["materiality_pass_rate"]),
                    _fmt(r["interaction_fire_rate"]),
                    _fmt(r["selection_limited_rate"]),
                ]
            )
            + " \\\\"
        )

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")

    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    return "\n".join(lines)